name: CI

# Only trigger, when the test workflow succeeded
on: [push, pull_request]

jobs:
  build:
    if: |
      github.event_name == 'push' &&
      github.event.base_ref == 'refs/heads/main' &&
      startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Build REMS
        run: cargo build --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: rems
          path: ./target/release/rust-eldewrito-master-server

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: rems
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rems
